"""OpenCode plugin adapter — wraps VR hooks for OpenCode's plugin system."""

from __future__ import annotations

import sys
from pathlib import Path

_PLUGIN_TEMPLATE = """\
// VibesRails plugin for OpenCode
// Generated by: vibesrails --init-hooks opencode

const {{ execFileSync }} = require('child_process');

const PYTHON = '{python_path}';

function runHook(mod, input) {{
  try {{
    const result = execFileSync(
      PYTHON, ['-m', mod],
      {{ input: JSON.stringify(input), encoding: 'utf-8', timeout: 10000 }}
    );
    return {{ output: result.trim(), blocked: false }};
  }} catch (err) {{
    if (err.status === 1) return {{ output: (err.stdout || '').trim(), blocked: true }};
    return {{ output: '', blocked: false }};
  }}
}}

module.exports = function vibesrailsPlugin() {{
  return {{
    hooks: {{
      'tool.execute.before': (event) => {{
        const r = runHook('vibesrails.hooks.pre_tool_use', {{
          tool_name: event.tool?.name || '', tool_input: event.tool?.input || {{}},
        }});
        if (r.blocked) throw new Error(r.output);
      }},
      'tool.execute.after': (event) => {{
        runHook('vibesrails.hooks.post_tool_use', {{
          tool_name: event.tool?.name || '', tool_input: event.tool?.input || {{}},
        }});
      }},
    }},
  }};
}};
"""


def generate_opencode_plugin(root: Path) -> Path:
    """Generate .opencode/plugins/vibesrails.js."""
    plugins_dir = root / ".opencode" / "plugins"
    plugins_dir.mkdir(parents=True, exist_ok=True)
    path = plugins_dir / "vibesrails.js"
    path.write_text(_PLUGIN_TEMPLATE.format(python_path=sys.executable))
    return path
